Algoritmo "variaveisEoperadores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Yasmim
// Data atual  : 17/04/2022
Var
// Seção de Declarações das variáveis

soma: inteiro
media: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   soma <- 4+9+8+6+5
   media <- soma/5
   
         escreval("A soma é de: ", soma, " e a média é de: ", media)


Fimalgoritmo